# Copyright (C) 2023 psionicprjkt

name: build-ksu-oc

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Git Config
        run: |
          git config --global user.name "officialputuid"
          git config --global user.email officialputuid@hack.id

      - name: Clone Clang & Kernel Sources
        run: |
          git clone --depth=1 https://github.com/psionicprjkt/android_kernel_realme_mt6785 -b R-based-overclock mt6785
          cd mt6785
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r498229b.tar.gz -O "aosp-clang.tar.gz"
          mkdir clang && tar -xf aosp-clang.tar.gz -C clang && rm -f aosp-clang.tar.gz

      - name: Update Latest KernelSU
        run: |
          cd mt6785
          rm -rf KernelSU && curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

      - name: Trigger KSU+OC Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run ksu-oc.yml --ref R-based

      - name: Build Kernel
        run: |
          cd mt6785
          . build-ksu-oc.sh

      - name: Set Release Date
        run: |
          echo "RELEASE_DATE=$(date +"%d%m%Y")" >> "$GITHUB_ENV"

      - name: Release Kernel
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "KSU+OC"
          prerelease: false
          title: psionic-kernel-RM6785-${{ env.RELEASE_DATE }}-KSU+OC
          files: |
            mt6785/AnyKernel/psionic-kernel-RM6785*

