# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build-normal

on:
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
    - uses: actions/checkout@v2
    - run: |
          git config --global user.name "officialputuid"
          git config --global user.email officialputuid@hack.id

    - name: Clone sources
      run: |
          git clone https://github.com/psionicprjkt/android_kernel_realme_mt6785 mt6785
          git clone --depth=1 https://gitlab.com/LeCmnGend/proton-clang.git -b clang-16 mt6785/clang

    - name: Trigger ksu wf
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh workflow run ksu.yml --ref R-based

    - name: Revert KernelSU
      run: |
          cd mt6785
          git fetch https://github.com/psionicprjkt/android_kernel_realme_mt6785 R-based-nonksu
          git cherry-pick 4e563de0a4adb13f2dc1c38eff00e08ccb4a3c5b

    - name: Build Kernel
      run: |
          cd mt6785
          . build-normal.sh

    - name: Set Date
      run: |
          echo "RELEASE_DATE=$(date +"%d%m%Y")" >> "$GITHUB_ENV"

    - name: Release Kernel
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "Normal"
        prerelease: false
        title: psionic-kernel-RM6785-${{ env.RELEASE_DATE }}-Normal
        files: |
          mt6785/AnyKernel/psionic-kernel-RM6785*
